import { Emergency } from "./Cards/Cards"

export {default as Navbar} from "./Navbar/Navbar"
export {default as Footer} from "./Footer/Footer"
export {default as Flex} from "./Flex/Flex"
export {default as Service} from "./Service/Service"
export {default as MedicalService} from "./MedicalService/MedicalService"
export {default as Review} from "./Review/Review"
export {default as Map} from "./Map/Map"
export {default as Form} from "./Form/Form"
export {default as Cards} from "./Cards/Cards"
export {default as InfoCard} from "./Cards/InfoCard"
export {default as DoctorCard} from "./Cards/DoctorCard"
export {default as AppointmentForm} from "./AppointmentForm/AppointmentForm"
export {default as AboutComponent} from "./AboutComponent/AboutComponent"